apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: default # Change this to 'default' or another existing namespace
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: default # Change this to 'default' or another existing namespace
spec:
  selector:
    app: portainer
