apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: default # Change to your namespace if needed
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: default # Change to your namespace if needed
spec:
  selector:
    app: portainer
  ports:
    - protocol: TCP
      port: 80 # Port exposed externally
      targetPort: 9000 # Port inside the container
  type: NodePort
